//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace Pulsuz_Mesaj.AzinfServices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AzinfServiceBinding", Namespace="http://yoxlama.com/soap/AzinfService")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MySoapObject))]
    public partial class AzinfService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback returnNewsArrayOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AzinfService() {
            this.Url = global::Pulsuz_Mesaj.Properties.Settings.Default.Pulsuz_Mesaj_Services_SimpleService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event returnNewsArrayCompletedEventHandler returnNewsArrayCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://yoxlama.com/azinf/WebServices/getNews.php/returnNewsArray", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public MySoapObject[] returnNewsArray(string agent) {
            object[] results = this.Invoke("returnNewsArray", new object[] {
                        agent});
            return ((MySoapObject[])(results[0]));
        }
        
        /// <remarks/>
        public void returnNewsArrayAsync(string agent) {
            this.returnNewsArrayAsync(agent, null);
        }
        
        /// <remarks/>
        public void returnNewsArrayAsync(string agent, object userState) {
            if ((this.returnNewsArrayOperationCompleted == null)) {
                this.returnNewsArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreturnNewsArrayOperationCompleted);
            }
            this.InvokeAsync("returnNewsArray", new object[] {
                        agent}, this.returnNewsArrayOperationCompleted, userState);
        }
        
        private void OnreturnNewsArrayOperationCompleted(object arg) {
            if ((this.returnNewsArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.returnNewsArrayCompleted(this, new returnNewsArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://yoxlama.com/soap/AzinfService")]
    public partial class MySoapObject {
        
        private string newsTitleField;
        
        private string newsIdField;
        
        /// <remarks/>
        public string newsTitle {
            get {
                return this.newsTitleField;
            }
            set {
                this.newsTitleField = value;
            }
        }
        
        /// <remarks/>
        public string newsId {
            get {
                return this.newsIdField;
            }
            set {
                this.newsIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void returnNewsArrayCompletedEventHandler(object sender, returnNewsArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class returnNewsArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal returnNewsArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MySoapObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MySoapObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591